# Generated by Django 4.2.16 on 2025-09-05 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluminium', models.FloatField()),
                ('ammonia', models.FloatField()),
                ('arsenic', models.FloatField()),
                ('barium', models.FloatField()),
                ('cadmium', models.FloatField()),
                ('chloramine', models.FloatField()),
                ('chromium', models.FloatField()),
                ('copper', models.FloatField()),
                ('flouride', models.FloatField()),
                ('bacteria', models.FloatField()),
                ('viruses', models.FloatField()),
                ('lead', models.FloatField()),
                ('nitrates', models.FloatField()),
                ('nitrites', models.FloatField()),
                ('mercury', models.FloatField()),
                ('perchlorate', models.FloatField()),
                ('radium', models.FloatField()),
                ('selenium', models.FloatField()),
                ('silver', models.FloatField()),
                ('uranium', models.FloatField()),
                ('is_safe', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
